In [92]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import joblib
import warnings
warnings.filterwarnings("ignore")

In [93]:
df = pd.read_csv('./../part_1/heart_cleaned.csv')
df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up,MaxHR_ratio,Has_ST_Depression
0,40,140,289,0,172,0,0,1,1,0,0,1,0,0,0,1,0.955556,0
1,49,160,180,0,156,1,1,0,0,1,0,1,0,0,1,0,0.912281,1
2,37,130,283,0,98,0,0,1,1,0,0,0,1,0,0,1,0.535519,0
3,48,138,214,0,108,1,1,0,0,0,0,1,0,1,1,0,0.627907,1
4,54,150,195,0,122,0,0,1,0,1,0,1,0,0,0,1,0.734940,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1,1,1,0,0,1,1,0,0,1,0,0.754286,1
914,68,144,193,1,141,3,1,1,0,0,0,1,0,0,1,0,0.927632,1
915,57,130,131,0,115,1,1,1,0,0,0,1,0,1,1,0,0.705521,1
916,57,130,236,0,174,0,1,0,1,0,0,0,0,0,1,0,1.067485,0
917,38,138,175,0,173,0,0,1,0,1,0,1,0,0,0,1,0.950549,0

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   RestingBP          918 non-null    int64
 2   Cholesterol        918 non-null    int64
 3   FastingBS          918 non-null    int64
 4   MaxHR              918 non-null    int64
 5   Oldpeak            918 non-null    int64
 6   HeartDisease       918 non-null    int64
 7   Sex_M              918 non-null    int64
 8   ChestPainType_ATA  918 non-null    int64
 9   ChestPainType_NAP  918 non-null    int64
 10  ChestPainType_TA   918 non-null    int64
 11  RestingECG_Normal  918 non-null    int64
 12  RestingECG_ST      918 non-null    int64
 13  ExerciseAngina_Y   918 non-null    int64
 14  ST_Slope_Flat      918 non-null    int64
 15  ST_Slope_Up        918 non-null    int64
 16  MaxHR_ratio        918 non-null    float64
 17  Has_ST_Depression  918 non-null    int64
dtypes: float64(1), int64(17)
memory usage: 129.2 KB

In [95]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up,MaxHR_ratio,Has_ST_Depression
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.662309,244.516340,0.233115,136.809368,0.720044,0.553377,0.789760,0.188453,0.221133,0.050109,0.601307,0.193900,0.404139,0.501089,0.430283,0.821109,0.456427
std,9.432617,18.362202,53.318606,0.423046,25.460334,0.990165,0.497414,0.407701,0.391287,0.415236,0.218289,0.489896,0.395567,0.490992,0.500271,0.495386,0.142274,0.498369
min,28.000000,80.000000,85.000000,0.000000,60.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.355030,0.000000
25%,47.000000,120.000000,214.000000,0.000000,120.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.723270,0.000000
50%,54.000000,130.000000,244.000000,0.000000,138.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.825301,0.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.931570,1.000000
max,77.000000,244.000000,603.000000,1.000000,202.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.174699,1.000000

In [96]:
df.shape

(918, 18)

In [97]:
X = df.drop('HeartDisease',  axis=1)
y = df['HeartDisease']

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [99]:
scaler = StandardScaler()

X_train_standard_scaled = scaler.fit_transform(X_train)
X_test_standard_scaled = scaler.transform(X_test)

In [100]:
X_train_standard_scaled

array([[-1.24506731, -0.73515429, -0.10359418, ..., -0.84792072,
         1.92221455, -0.92386977],
       [-1.8862362 , -0.18638662, -0.71808371, ...,  1.17935554,
         1.05628108, -0.92386977],
       [ 0.25099346,  0.91114872, -0.63879474, ..., -0.84792072,
        -0.39426223,  1.08240364],
       ...,
       [ 0.67843939, -0.18638662,  0.15409499, ...,  1.17935554,
         0.57988817,  1.08240364],
       [ 0.67843939,  1.02090226, -0.0243052 , ...,  1.17935554,
        -0.56883343, -0.92386977],
       [-1.45879027,  0.91114872,  2.90938678, ..., -0.84792072,
        -0.6768329 ,  1.08240364]], shape=(734, 17))

In [101]:
models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Decision tree": DecisionTreeClassifier(),
    "SVM": SVC()
}

In [102]:
result = []

In [103]:
for name, model in models.items():
    model.fit(X_train_standard_scaled, y_train)

    y_pred = model.predict(X_test_standard_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    result.append({
        'model': name,
        'accuracy': round(accuracy, 4),
        'f1': round(f1, 4)
    })

In [104]:
result

[{'model': 'Logistic Regression', 'accuracy': 0.8587, 'f1': 0.8738},
 {'model': 'KNN', 'accuracy': 0.837, 'f1': 0.8544},
 {'model': 'Naive Bayes', 'accuracy': 0.837, 'f1': 0.85},
 {'model': 'Decision tree', 'accuracy': 0.8152, 'f1': 0.835},
 {'model': 'SVM', 'accuracy': 0.8424, 'f1': 0.8626}]

In [105]:
model = joblib.load("logistic_heart.pkl")
scaler = joblib.load("scaler.pkl")
columns = joblib.load("columns.pkl")

print(model)
print(scaler)
print(columns)

LogisticRegression()
StandardScaler()
['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST', 'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up', 'MaxHR_ratio', 'Has_ST_Depression']